### ISSUE TITLE
New Extension for ciscowebex

### ISSUE THREAD

**Issue by SamanFekri** [PoliNetwork/polinetwork.github.io#167]
Hey I make an extension for cisco webex, It handles events on the keyboard like pause and play the video with space, etc.

how can I change it to here to all Polimi students find it?

Extension is [here](https://github.com/SamanFekri/CiscoWebexHelper)

**Comment by ArmeF97** [comment]
Does your extensions work on firefox?

**Comment by SamanFekri** [comment]
Nope it just works in chrome

**Comment by ArmeF97** [comment]
Contact https://t.me/EliaMaggioni
