### ISSUE TITLE
Realizzare la versione inglese di tutte le pagine

### ISSUE THREAD

**Issue by PoliNetwork** [PoliNetwork/polinetwork.github.io#2]
Bisognerebbe mettere le bandiere da qualche parte in alto, con un po' scurita quella in uso

**Comment by ArmeF97** [comment]
Ho messo le bandierine nelle 2 pagine che ci sono per ora (home e extra), e in quella iniziale (prima ancora della home) ho messo un redirect alla home italiana se la lingua del browser è ita, altrimenti redirect a inglese

**Comment by ArmeF97** [comment]
Ok, si può iniziare con questo issue. 
Ho iniziato a fare qualcosa, man mano traduco (e magari anche meglio) le varie pagine

**Comment by ArmelliniFederico** [comment]
Con i commit sono andato avanti

**Comment by ArmeF97** [comment]
Quasi fatto, completo all' 80% diciamo

**Comment by ArmeF97** [comment]
fatto
